version: '2'
services:
  appcreator-app:
    image: appcreator
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mariadb://appcreator-mariadb:3306/appcreator
      - JHIPSTER_SLEEP=120 # gives time for mariadb server to start
    ports:
      - 80:80
  appcreator-mariadb:
    extends:
      file: mariadb.yml
      service: appcreator-mariadb
